// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYCo8PJAqdbEpvNcpKwTIke0sUbODf9Zc',
    appId: '1:922226543812:web:40229a6af3e4047d434d91',
    messagingSenderId: '922226543812',
    projectId: 'tesismolinadibernardi',
    authDomain: 'tesismolinadibernardi.firebaseapp.com',
    storageBucket: 'tesismolinadibernardi.firebasestorage.app',
    measurementId: 'G-4DVJM3H0LG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5cYLau5Llt9E2KE9EPAQsbj058XF-XL8',
    appId: '1:922226543812:android:f5a3bf0de4cdbd18434d91',
    messagingSenderId: '922226543812',
    projectId: 'tesismolinadibernardi',
    storageBucket: 'tesismolinadibernardi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxs674oHJcu8yY0B-1Ov6sZWa-CiFaDdo',
    appId: '1:922226543812:ios:57296416b225ebdb434d91',
    messagingSenderId: '922226543812',
    projectId: 'tesismolinadibernardi',
    storageBucket: 'tesismolinadibernardi.firebasestorage.app',
    iosBundleId: 'com.codigocorrecto.crudFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxs674oHJcu8yY0B-1Ov6sZWa-CiFaDdo',
    appId: '1:922226543812:ios:57296416b225ebdb434d91',
    messagingSenderId: '922226543812',
    projectId: 'tesismolinadibernardi',
    storageBucket: 'tesismolinadibernardi.firebasestorage.app',
    iosBundleId: 'com.codigocorrecto.crudFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYCo8PJAqdbEpvNcpKwTIke0sUbODf9Zc',
    appId: '1:922226543812:web:93b7d7bf7dd8257b434d91',
    messagingSenderId: '922226543812',
    projectId: 'tesismolinadibernardi',
    authDomain: 'tesismolinadibernardi.firebaseapp.com',
    storageBucket: 'tesismolinadibernardi.firebasestorage.app',
    measurementId: 'G-TE59ZZM9K7',
  );
}
